siteTitle = "Kristoffer Hedstrom"
url = "https://k-create.com"
name = "Kristoffer Hedstrom"
email = "hello@k-create.com"
segment = "KrpuBOMB62nTKrcoFBpMoZQEKKIJllxU"
description = "Website for Kristoffer Hedstrom: Interactive designer and developer from Brooklyn, NY"
twitter = "@_kris"
shareImage = "https://k-create.com/images/shakey-2.gif"
